name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get previous version
        id: prev_version
        run: |
          PREV_VERSION=$(node -p "require('./package.json').version")
          echo "prev_version=$PREV_VERSION" >> $GITHUB_OUTPUT
          echo "Previous version: $PREV_VERSION"

      - name: Analyze conventional commits and determine version bump
        id: version_bump
        run: |
          # Get commits since last tag or from development branch
          if git tag --sort=-version:refname | head -1 > /dev/null 2>&1; then
            LAST_TAG=$(git tag --sort=-version:refname | head -1)
            COMMITS=$(git log --oneline $LAST_TAG..HEAD --pretty=format:"%s")
          else
            # If no tags exist, get commits from development branch
            COMMITS=$(git log --oneline origin/development..HEAD --pretty=format:"%s")
          fi
          
          echo "Analyzing conventional commits:"
          echo "$COMMITS"
          
          # Check for feat commits (minor bump)
          FEAT_COUNT=$(echo "$COMMITS" | grep -c "^feat" || true)
          # Check for fix commits (patch bump)
          FIX_COUNT=$(echo "$COMMITS" | grep -c "^fix" || true)
          
          echo "feat commits: $FEAT_COUNT"
          echo "fix commits: $FIX_COUNT"
          
          if [ "$FEAT_COUNT" -gt 0 ]; then
            echo "bump_type=minor" >> $GITHUB_OUTPUT
            echo "Version bump: minor (feat commits found)"
          elif [ "$FIX_COUNT" -gt 0 ]; then
            echo "bump_type=patch" >> $GITHUB_OUTPUT
            echo "Version bump: patch (fix commits found)"
          else
            echo "bump_type=none" >> $GITHUB_OUTPUT
            echo "No version bump needed (no feat/fix commits)"
          fi

      - name: Bump version
        id: bump_version
        if: steps.version_bump.outputs.bump_type != 'none'
        run: |
          BUMP_TYPE="${{ steps.version_bump.outputs.bump_type }}"
          echo "Bumping $BUMP_TYPE version..."
          
          # Bump version using npm version
          NEW_VERSION=$(npm version $BUMP_TYPE --no-git-tag-version)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Generate changelog
        id: changelog
        run: |
          # Get commits since last tag or from development branch
          if git tag --sort=-version:refname | head -1 > /dev/null 2>&1; then
            LAST_TAG=$(git tag --sort=-version:refname | head -1)
            COMMITS=$(git log $LAST_TAG..HEAD --pretty=format:"- %s (%h)" --grep="^feat\|^fix\|^docs\|^style\|^refactor\|^perf\|^test\|^chore\|^ci\|^build\|^revert")
          else
            COMMITS=$(git log origin/development..HEAD --pretty=format:"- %s (%h)" --grep="^feat\|^fix\|^docs\|^style\|^refactor\|^perf\|^test\|^chore\|^ci\|^build\|^revert")
          fi
          
          # Generate changelog header
          CHANGELOG_HEADER="## Changes in ${{ steps.bump_version.outputs.new_version || steps.prev_version.outputs.prev_version }}"
          CHANGELOG_FOOTER="**Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.prev_version.outputs.prev_version }}...${{ steps.bump_version.outputs.new_version || steps.prev_version.outputs.prev_version }}"
          
          # Combine all parts
          CHANGELOG="${CHANGELOG_HEADER}\n\n${COMMITS}\n\n${CHANGELOG_FOOTER}"
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo -e "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "Generated changelog:"
          echo -e "$CHANGELOG"

      - name: Build project
        run: |
          yarn build
          echo "Build completed successfully"

      - name: Commit version bump
        if: steps.version_bump.outputs.bump_type != 'none'
        run: |
          git add package.json
          git commit -m "chore: bump version to ${{ steps.bump_version.outputs.new_version }}"
          git push origin master

      - name: Create Git tag
        if: steps.version_bump.outputs.bump_type != 'none'
        run: |
          git tag -a "${{ steps.bump_version.outputs.new_version }}" -m "Release ${{ steps.bump_version.outputs.new_version }}"
          git push origin "${{ steps.bump_version.outputs.new_version }}"

      - name: Create GitHub Release
        if: steps.version_bump.outputs.bump_type != 'none'
        run: |
          gh release create "${{ steps.bump_version.outputs.new_version }}" \
            --title "Release ${{ steps.bump_version.outputs.new_version }}" \
            --notes "${{ steps.changelog.outputs.changelog }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Publish to npm
    #     if: steps.version_bump.outputs.bump_type != 'none'
    #     run: |
    #       echo "Publishing to npm..."
    #       # Note: You'll need to add NPM_TOKEN to secrets for this to work
    #       # echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    #       # npm publish
    #       echo "Skipping npm publish (requires NPM_TOKEN secret)"
